//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_application_UX.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI_application_UX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   奈良県にある、聖徳太子ゆかりの由緒ある寺院です。五重塔や金堂など、世界最古の木造建築群が当時の姿のまま残されており、1993年に日本初の世界文化遺産として登録されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CardDesc_houryuzi {
            get {
                return ResourceManager.GetString("CardDesc_houryuzi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   東京・お台場にそびえ立つ実物大のガンダム立像。日本の圧倒的な技術力とアニメ文化の融合を象徴する、現代の新たな「文化遺産」とも呼べる大迫力のモニュメントです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CardDesc_Unicorn {
            get {
                return ResourceManager.GetString("CardDesc_Unicorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   法隆寺 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CardTitle_houryuzi {
            get {
                return ResourceManager.GetString("CardTitle_houryuzi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユニコーン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CardTitle_Unicorn {
            get {
                return ResourceManager.GetString("CardTitle_Unicorn", resourceCulture);
            }
        }
    }
}
